version: '3.4'

services:
  gymgenius:
    container_name: gymgenius_api
    image: ${DOCKER_REGISTRY-}gymgenius
    build:
      context: .
      dockerfile: GymGenius/Dockerfile
    ports:
      - "80:80"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: always
    environment:
      SA_PASSWORD: "qwer1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
