version: '3.4'

services:
  gymgenius:
    container_name: gymgenius_api
    image: ${DOCKER_REGISTRY-}gymgenius
    build:
      context: .
      dockerfile: GymGenius/Dockerfile
    ports:
      - "80:80"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: always
    environment:
      SA_PASSWORD: "Qwer1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Qwer1234! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql-tools
    volumes:
      - ./Gymgenius/init:/docker-entrypoint-initdb.d
    depends_on:
      mssql:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Qwer1234! -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '